In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

sns.set()

# I/ Importation des données

### I.A/ Fichiers uniques

In [2]:
# Import des données
df_sales = pd.read_csv("DATA/df_sales.csv")
df_events = pd.read_csv("DATA/df_events.csv")
df_customers = pd.read_csv("DATA/df_customers.csv")

# Suppression des colonnes inutiles
df_sales = df_sales[df_sales.columns.drop(['Unnamed: 0'])]
df_customers=df_customers[df_customers.columns.drop(['Unnamed: 0'])]
df_events=df_events[df_events.columns.drop(['Unnamed: 0'])]

# Conversion des types
df_sales['id_client']=df_sales['id_client'].astype(str)
df_customers['ID']=df_customers['ID'].astype(str)

df_sales.head()

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608

### I.B/ Jointure des données

In [3]:
# Jointure des données
df_temp = pd.merge(left=df_sales, right=df_events, left_on='source', right_on='Source')
df_temp = pd.merge(left=df_temp, right=df_customers, left_on='id_client', right_on='ID')
print(f"Nombre de lignes : {df_temp.shape[0]}")
df_temp.head()

Nombre de lignes : 13703

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source,ID_x,begin_on,ville,Source,Lieu,Type_Lieu,ID_y,sexe,DDN,sub,sub_notif,sub_newsletter
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,3753,F,2005-05-19,NaN,NaN,NaN
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,1323,F,2003-01-01,0.0,0.0,0.0
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,3743,F,NaN,NaN,NaN,NaN
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,1432,F,2005-01-01,0.0,0.0,0.0
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,4657,NaN,2001-01-01,0.0,0.0,0.0

# II/ Préparation des données

### II.A/ Conversion des types

In [20]:
# Suppression des colonnes superflues
drop_columns = ['ID_x', 'ID_y']
df_work = df_temp[df_temp.columns.drop(drop_columns)]

# Changement des types
df_work['date_creation'] = pd.to_datetime(df_work['date_creation'])
df_work['date_utilisation'] = pd.to_datetime(df_work['date_utilisation'])
df_work['begin_on'] = pd.to_datetime(df_work['begin_on'])
df_work['DDN'] = pd.to_datetime(df_work['DDN'])

df_work.head()

/tmp/ipykernel_168023/1292748174.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_creation'] = pd.to_datetime(df_work['date_creation'])
/tmp/ipykernel_168023/1292748174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_utilisation'] = pd.to_datetime(df_work['date_utilisation'])
/tmp/ipykernel_168023/1292748174.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['begin_on'] = pd.to_datetime(df_work['begin_on'])
/tmp/ipykernel_168023/1292748174.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['DDN'] = pd.to_datetime(df_work['DDN'])

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source,begin_on,ville,Source,Lieu,Type_Lieu,sexe,DDN,sub,sub_notif,sub_newsletter
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2005-05-19,NaN,NaN,NaN
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2003-01-01,0.0,0.0,0.0
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,NaT,NaN,NaN,NaN
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2005-01-01,0.0,0.0,0.0
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,NaN,2001-01-01,0.0,0.0,0.0

In [5]:
# Affichage des types 
df_work.dtypes

id_billet                    int64
commande                     int64
date_creation       datetime64[ns]
id_client                   object
prix                       float64
date_utilisation    datetime64[ns]
source                      object
begin_on            datetime64[ns]
ville                       object
Source                      object
Lieu                        object
Type_Lieu                   object
sexe                        object
DDN                 datetime64[ns]
sub                        float64
sub_notif                  float64
sub_newsletter             float64
dtype: object

### II.B/ Traitement des valeurs nulles

In [6]:
# Affichage des taux de remplissage des 
df_work.notnull().mean()

id_billet           1.000000
commande            1.000000
date_creation       1.000000
id_client           1.000000
prix                1.000000
date_utilisation    0.799241
source              1.000000
begin_on            1.000000
ville               1.000000
Source              1.000000
Lieu                1.000000
Type_Lieu           1.000000
sexe                0.872510
DDN                 0.856820
sub                 0.356053
sub_notif           0.356053
sub_newsletter      0.380793
dtype: float64

In [7]:
### Date utilisation
# Calcule des médianes groupées
df_work['date_utilisation'] = df_work['date_utilisation'].fillna(
    df_work.groupby('source')['date_utilisation']
           .transform(lambda x: x.dropna().median())
)

### Sexe
df_work['sexe']=df_work['sexe'].replace({'1':'F', '0':'M'}) # Formatage des données pour n'avoir que 2 modalités
df_work['sexe']=df_work['sexe'].fillna(value=df_work['sexe'].mode()[0])

### DDN
df_work['DDN']=df_work['DDN'].fillna(df_work['DDN'].median())

### sub, sub_notif, sub_newsletter
df_work['sub']=df_work['sub'].fillna(0)
df_work['sub_notif']=df_work['sub_notif'].fillna(0)
df_work['sub_newsletter']=df_work['sub_newsletter'].fillna(0)

/tmp/ipykernel_168023/2936186222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_utilisation'] = df_work['date_utilisation'].fillna(
/tmp/ipykernel_168023/2936186222.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sexe']=df_work['sexe'].replace({'1':'F', '0':'M'}) # Formatage des données pour n'avoir que 2 modalités
/tmp/ipykernel_168023/2936186222.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sexe']=df_work['sexe'].fillna(value=df_work['sexe'].mode()[0])
/tmp/ipykernel_168023/2936186222.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['DDN']=df_work['DDN'].fillna(df_work['DDN'].median())
/tmp/ipykernel_168023/2936186222.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub']=df_work['sub'].fillna(0)
/tmp/ipykernel_168023/2936186222.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub_notif']=df_work['sub_notif'].fillna(0)
/tmp/ipykernel_168023/2936186222.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub_newsletter']=df_work['sub_newsletter'].fillna(0)

### II.C/ Création de variables

In [8]:
# Âge du client
df_work['age_event'] = (df_work['date_creation'] - df_work['DDN']).dt.days // 365

# Anticipation
df_work['anticipation']=(df_work['begin_on'] - df_work['date_creation']).dt.days

# Année et mois de l'évènement
df_work['begin_on_year'] = df_work['begin_on'].dt.year
df_work['begin_on_month'] = df_work['begin_on'].dt.month
df_work['JDS'] = df_work['date_creation'].dt.dayofweek

/tmp/ipykernel_168023/2721480199.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['age_event'] = (df_work['date_creation'] - df_work['DDN']).dt.days // 365

### II.D/ Questions

##### II.D.1/ Dans quelle salle?

In [9]:
# Création des dépenses par client pour chaque évènement
df_agg = df_work.groupby(['Lieu', 'id_client'])['prix'].sum().reset_index()

# Affichage des moyennes de dépense par client sur chaque évènement
df_agg.groupby(['Lieu'])['prix'].mean().sort_values(ascending=False).head()

Lieu
Salle Turquoise    33.791615
Salle Jaune        29.460472
Salle Grise        29.313957
Salle Rose         29.249892
Salle Verte        27.369881
Name: prix, dtype: float64

##### II.D.2/ En pourcentage ?...

In [10]:
df_sales_year = df_work.groupby('begin_on_year').size() # Calcul des volumes par années
df_plot = df_sales_year.pct_change() * 100 # Calcul des évolution par années
df_plot

begin_on_year
2022           NaN
2023    233.836858
2024     51.719457
2025    123.024157
dtype: float64

In [16]:
import matplotlib.pyplot as plt
%pip install matplotlib-inline

df_plot.plot(kind='bar')
plt.title('Évolution du volume de billet par année')
plt.show()

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Note: you may need to restart the kernel to use updated packages.

ModuleNotFoundError: No module named 'matplotlib_inline'

##### II.D.3/ Anticipation médiane

In [17]:
# Isolement à 
df_sales_2025 = df_work[(df_work['begin_on_year']==2025)]
df_sales_2025['anticipation'].median()

-1.0

##### II.D.4/ Quelle age et ou?

In [18]:
# Obtention d'une table par client et par évènement
df_filtered=df_work[['source', 'ville','id_client', 'age_event']].drop_duplicates()

# Calcul des valeurs
df_filtered.groupby('ville')['age_event'].mean().sort_values(ascending=False)

ville
Paris     23.229851
Nantes    21.705706
Lille     21.155782
Name: age_event, dtype: float64

# III/ Table client

### III.A/ Création de la table

##### III.A.1/ Calcul groupés intermédiaires

In [21]:
# Calcul des montants clients
df_clients = (
    df_work
        .groupby('id_client')
        .agg(
            DDN_max=('DDN', 'max'),
            sexe_mode=('sexe', lambda x: x.mode().iloc[0]),
            prix_total=('prix', 'sum'),
            nb_billets=('id_billet', 'nunique'),
            nb_commandes=('commande', 'nunique'),
            nb_sources=('source', 'nunique'),
            anticipation_moy=('anticipation', 'mean'),
            date_creation_min=('date_creation', 'min'),
            date_creation_max=('date_creation', 'max')
        )
        .reset_index()
)

# Calcul de l'âge des clients
df_clients['age'] = (datetime.datetime.now() - df_clients['DDN_max']).dt.days // 365

# Création de colonnes calculées
df_clients['prix_billets_moy'] = df_clients['prix_total'] / df_clients['nb_billets']
df_clients['billets_par_commandes'] = df_clients['nb_billets'] / df_clients['nb_commandes']
df_clients['DDV'] = (df_clients['date_creation_max'] - df_clients['date_creation_min']).dt.days
df_clients['DDV'] = np.maximum(df_clients['DDV'], 1)
df_clients['DDV_annee'] = df_clients['DDV'] / 365
df_clients['DDV_mois'] = df_clients['DDV_annee'] * 12
df_clients['recence'] = (datetime.datetime.now() - df_clients['date_creation_max']).dt.days

### Calcul du score RFM
# Calcul des scores
df_clients['R_score'] = pd.qcut(
    df_clients['recence'],
    q=5,
    labels=range(5, 0, -1)
).astype(str)

df_clients['F_score'] = pd.qcut(
    df_clients['nb_commandes'].rank(method='first'),
    q=5,
    labels=range(1, 6)
).astype(str)

df_clients['M_score'] = pd.qcut(
    df_clients['prix_total'],
    q=5,
    labels=range(1, 6)
).astype(str)

# Création du score concaténé
df_clients['RFM'] = df_clients['R_score'] + df_clients['F_score'] + df_clients['M_score']

df_clients.head()

KeyError: "Column(s) ['anticipation'] do not exist"

##### III.A.2/ Calcul groupés avancés


- 1 table par décomposition tel que le produit des colonnes nous donne le CA
- niv 1 : nb_clients x panier_moyen
- niv 2 : nb_clients x nb_billets x pm_billets
- niv 3 : nb_clients x CA_moyen_periode x DDV
- Décomposer selon plusieurs critères : Sexe, TA, Anticipation, RFM

In [ ]:
### Création de varibale qualitative à ventiler
# Âge
bins = [0, 20, 23, 26, np.inf]
labels = [
    "-20 ans",
    "20-22 ans",
    "23-25 ans",
    "+25 ans"
]

df_clients['age_categorie'] = pd.cut(
    df_clients['age'],
    bins=bins,
    labels=labels,
    right=False  # bornes inclusives à gauche
)

# Anticipation
bins = [-np.inf, 1, 6, 13,np.inf]
labels = [
    'J-J',
    'S1', 'S2', '+S2'
]

df_clients['anticipation_categorie'] = pd.cut(
    df_clients['anticipation_moy'],
    bins=bins,
    labels=labels,
    right=False  # bornes inclusives à gauche
)

# RFM
# TBC : Très bon client
# CF : Client Fidèle
# CR : Client Récens
# CPP : Client à ne pas perdre
# CEV :  Client en veille
# CP : Client Perdus
# NA : Non caractérisé

rfm_dict = {
    # TBC
    '555': 'TBC',

    # CF
    '554': 'CF', '545': 'CF', '455': 'CF',
    '544': 'CF', '445': 'CF', '454': 'CF', '444': 'CF',

    # CR
    '511': 'CR', '512': 'CR', '513': 'CR', '514': 'CR', '515': 'CR',
    '521': 'CR', '522': 'CR', '523': 'CR', '524': 'CR', '525': 'CR',
    '531': 'CR', '532': 'CR', '534': 'CR', '535': 'CR',

    '411': 'CR', '412': 'CR', '413': 'CR', '414': 'CR', '415': 'CR',
    '421': 'CR', '422': 'CR', '423': 'CR', '424': 'CR', '425': 'CR',
    '431': 'CR', '432': 'CR', '433': 'CR', '434': 'CR', '435': 'CR',

    # CPP
    '355': 'CPP', '345': 'CPP', '354': 'CPP', '344': 'CPP',

    # CEV
    '333': 'CEV', '332': 'CEV', '331': 'CEV',
    '323': 'CEV', '322': 'CEV', '321': 'CEV',
    '313': 'CEV', '312': 'CEV', '311': 'CEV',

    # CP
    '111': 'CP', '112': 'CP', '113': 'CP',
    '121': 'CP', '122': 'CP', '123': 'CP',
    '131': 'CP', '132': 'CP', '133': 'CP',
    '211': 'CP', '212': 'CP', '213': 'CP',
    '221': 'CP', '222': 'CP', '223': 'CP',
    '231': 'CP', '232': 'CP', '233': 'CP'
}
df_clients['RFM_cat'] = df_clients['RFM'].map(rfm_dict).fillna('NA')
ordre_RFM=['TBC', 'CF', 'CR', 'CPP', 'CEV', 'CP', 'NA']

### III.B/ Analyse de la base client

Pour chaque dataframe, remplacer la valeur de var par la colonne avec laquelle vous souhitez ventiler vos résultats. Voici quelques examples : 

- sexe_mode : genre des clients
- age_categorie : Tranche d'âge des clients
- anticipation_categorie : Catégorie sur le comportement d'achat du client
- RFM_cat : Catégorie RFM

##### III.B.1/ CA = nb_client x Panier moyen

In [ ]:
var='age_categorie'
categorie_client = ["TBC", "CF", "CR", "CPP", "CEV", "CP", "NA"]

df_decompo = df_clients.groupby("RFM_cat").agg(
    CA = ('prix_total', 'sum'),
    PM = ('prix_total', 'mean'),
    tot_client=('id_client', 'nunique')
).sort_index()
df_decompo

               CA          PM  tot_client
RFM_cat
CEV       8783.01   13.723453         640
CF       31900.51   53.079052         601
CP       16481.20   13.410252        1229
CPP      16611.35   53.412701         311
CR       29473.99   20.625605        1429
NA       63673.63   30.277523        2103
TBC      20751.84  113.398033         183

##### III.B.2/ CA = nb_client x nb_billets x prix_moyen_billet

In [ ]:
var='age_categorie'
df_decompo = df_clients.groupby(var).agg(
    CA = ('prix_total', 'sum'),
    PM_billet = ('prix_billets_moy', 'mean'),
    nb_billets_moyens = ('nb_billets', 'mean'),
    tot_client=('id_client', 'nunique')
).sort_index()

df_decompo

/tmp/ipykernel_28554/2650413274.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_decompo = df_clients.groupby(var).agg(

                     CA  PM_billet  nb_billets_moyens  tot_client
age_categorie
-20 ans        10498.61  14.413668           1.584052         464
20-22 ans      97083.42  13.781516           2.168939        3374
23-25 ans      51953.45  14.517623           2.198096        1681
+25 ans        28140.05  15.010875           2.001024         977

##### III.B.1/ CA = nb_client x prix_moyen_billet x DDV_par_mois x nb_achat_par_mois

In [ ]:
var='age_categorie'
df_decompo = df_clients.groupby(var).agg(
    CA = ('prix_total', 'sum'),
    PM_billet = ('prix_billets_moy', 'mean'),
    nb_billets_moyens = ('nb_billets', 'mean'),
    DDV_mois_moy = ('DDV_mois', 'mean'),
    tot_client=('id_client', 'nunique')
).sort_index()

df_decompo['nb_billets_par_mois'] = df_decompo['nb_billets_moyens'] / df_decompo['DDV_mois_moy']

df_decompo[['CA', 'PM_billet', 'nb_billets_par_mois', 'DDV_mois_moy', 'tot_client']]

/tmp/ipykernel_28554/2053994158.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_decompo = df_clients.groupby(var).agg(

,CA,PM_billet,nb_billets_par_mois,DDV_mois_moy,tot_client
age_categorie,,,,,
-20 ans,10498.61,14.413668,2.365991,0.669509,464
20-22 ans,97083.42,13.781516,1.076324,2.015136,3374
23-25 ans,51953.45,14.517623,0.766631,2.867217,1681
+25 ans,28140.05,15.010875,1.216542,1.644845,977